import spotifyApi from "@/lib/spotify";
import { NextApiRequest, NextApiResponse } from "next";
import { getToken } from "next-auth/jwt";

export default async function GET(req: NextApiRequest, res: NextApiResponse) {
  if (req.method != "GET")
    return res.status(405).json({
      message: "Invaid Method ! EXPECTED: GET method.",
      status: 405,
    });

  try {
    // return res.status(200).json({
    //   data: {
    //     device: {
    //       id: "087ef49f5795f18e078b66c10b234ba3701aa67b",
    //       is_active: true,
    //       is_private_session: false,
    //       is_restricted: false,
    //       name: "Marban's Reno11",
    //       supports_volume: false,
    //       type: "Smartphone",
    //       volume_percent: 100,
    //     },
    //     shuffle_state: true,
    //     smart_shuffle: false,
    //     repeat_state: "off",
    //     timestamp: 1712033840438,
    //     context: {
    //       external_urls: {
    //         spotify: "https://open.spotify.com/playlist/4H83eHQnHMY4zpS1rm79Qz",
    //       },
    //       href: "https://api.spotify.com/v1/playlists/4H83eHQnHMY4zpS1rm79Qz",
    //       type: "playlist",
    //       uri: "spotify:playlist:4H83eHQnHMY4zpS1rm79Qz",
    //     },
    //     progress_ms: 84965,
    //     item: {
    //       album: {
    //         album_type: "album",
    //         artists: [
    //           {
    //             external_urls: {
    //               spotify:
    //                 "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz",
    //             },
    //             href: "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
    //             id: "4MCBfE4596Uoi2O4DtmEMz",
    //             name: "Juice WRLD",
    //             type: "artist",
    //             uri: "spotify:artist:4MCBfE4596Uoi2O4DtmEMz",
    //           },
    //         ],
    //         available_markets: [
    //           "AR",
    //           "AU",
    //           "AT",
    //           "BE",
    //           "BO",
    //           "BR",
    //           "BG",
    //           "CA",
    //           "CL",
    //           "CO",
    //           "CR",
    //           "CY",
    //           "CZ",
    //           "DK",
    //           "DO",
    //           "DE",
    //           "EC",
    //           "EE",
    //           "SV",
    //           "FI",
    //           "FR",
    //           "GR",
    //           "GT",
    //           "HN",
    //           "HK",
    //           "HU",
    //           "IS",
    //           "IE",
    //           "IT",
    //           "LV",
    //           "LT",
    //           "LU",
    //           "MY",
    //           "MT",
    //           "MX",
    //           "NL",
    //           "NZ",
    //           "NI",
    //           "NO",
    //           "PA",
    //           "PY",
    //           "PE",
    //           "PH",
    //           "PL",
    //           "PT",
    //           "SG",
    //           "SK",
    //           "ES",
    //           "SE",
    //           "CH",
    //           "TW",
    //           "TR",
    //           "UY",
    //           "US",
    //           "GB",
    //           "AD",
    //           "LI",
    //           "MC",
    //           "ID",
    //           "JP",
    //           "TH",
    //           "VN",
    //           "RO",
    //           "IL",
    //           "ZA",
    //           "SA",
    //           "AE",
    //           "BH",
    //           "QA",
    //           "OM",
    //           "KW",
    //           "EG",
    //           "MA",
    //           "DZ",
    //           "TN",
    //           "LB",
    //           "JO",
    //           "PS",
    //           "IN",
    //           "BY",
    //           "KZ",
    //           "MD",
    //           "UA",
    //           "AL",
    //           "BA",
    //           "HR",
    //           "ME",
    //           "MK",
    //           "RS",
    //           "SI",
    //           "KR",
    //           "BD",
    //           "PK",
    //           "LK",
    //           "GH",
    //           "KE",
    //           "NG",
    //           "TZ",
    //           "UG",
    //           "AG",
    //           "AM",
    //           "BS",
    //           "BB",
    //           "BZ",
    //           "BT",
    //           "BW",
    //           "CV",
    //           "CW",
    //           "DM",
    //           "FJ",
    //           "GM",
    //           "GE",
    //           "GD",
    //           "GW",
    //           "GY",
    //           "HT",
    //           "JM",
    //           "KI",
    //           "LS",
    //           "LR",
    //           "MW",
    //           "MV",
    //           "ML",
    //           "MH",
    //           "FM",
    //           "NA",
    //           "NR",
    //           "NE",
    //           "PW",
    //           "PG",
    //           "WS",
    //           "SM",
    //           "ST",
    //           "SN",
    //           "SC",
    //           "SL",
    //           "SB",
    //           "KN",
    //           "LC",
    //           "VC",
    //           "SR",
    //           "TL",
    //           "TO",
    //           "TT",
    //           "TV",
    //           "VU",
    //           "AZ",
    //           "BI",
    //           "KH",
    //           "CM",
    //           "TD",
    //           "KM",
    //           "GQ",
    //           "SZ",
    //           "GA",
    //           "GN",
    //           "KG",
    //           "LA",
    //           "MO",
    //           "MR",
    //           "MN",
    //           "NP",
    //           "RW",
    //           "TG",
    //           "UZ",
    //           "ZW",
    //           "BJ",
    //           "MG",
    //           "MU",
    //           "MZ",
    //           "AO",
    //           "CI",
    //           "DJ",
    //           "ZM",
    //           "CD",
    //           "CG",
    //           "IQ",
    //           "LY",
    //           "TJ",
    //           "VE",
    //           "ET",
    //           "XK",
    //         ],
    //         external_urls: {
    //           spotify: "https://open.spotify.com/album/6tkjU4Umpo79wwkgPMV3nZ",
    //         },
    //         href: "https://api.spotify.com/v1/albums/6tkjU4Umpo79wwkgPMV3nZ",
    //         id: "6tkjU4Umpo79wwkgPMV3nZ",
    //         images: [
    //           {
    //             height: 640,
    //             url: "https://i.scdn.co/image/ab67616d0000b273f7db43292a6a99b21b51d5b4",
    //             width: 640,
    //           },
    //           {
    //             height: 300,
    //             url: "https://i.scdn.co/image/ab67616d00001e02f7db43292a6a99b21b51d5b4",
    //             width: 300,
    //           },
    //           {
    //             height: 64,
    //             url: "https://i.scdn.co/image/ab67616d00004851f7db43292a6a99b21b51d5b4",
    //             width: 64,
    //           },
    //         ],
    //         name: "Goodbye & Good Riddance",
    //         release_date: "2018-12-10",
    //         release_date_precision: "day",
    //         total_tracks: 17,
    //         type: "album",
    //         uri: "spotify:album:6tkjU4Umpo79wwkgPMV3nZ",
    //       },
    //       artists: [
    //         {
    //           external_urls: {
    //             spotify:
    //               "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz",
    //           },
    //           href: "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
    //           id: "4MCBfE4596Uoi2O4DtmEMz",
    //           name: "Juice WRLD",
    //           type: "artist",
    //           uri: "spotify:artist:4MCBfE4596Uoi2O4DtmEMz",
    //         },
    //       ],
    //       available_markets: [
    //         "AR",
    //         "AU",
    //         "AT",
    //         "BE",
    //         "BO",
    //         "BR",
    //         "BG",
    //         "CA",
    //         "CL",
    //         "CO",
    //         "CR",
    //         "CY",
    //         "CZ",
    //         "DK",
    //         "DO",
    //         "DE",
    //         "EC",
    //         "EE",
    //         "SV",
    //         "FI",
    //         "FR",
    //         "GR",
    //         "GT",
    //         "HN",
    //         "HK",
    //         "HU",
    //         "IS",
    //         "IE",
    //         "IT",
    //         "LV",
    //         "LT",
    //         "LU",
    //         "MY",
    //         "MT",
    //         "MX",
    //         "NL",
    //         "NZ",
    //         "NI",
    //         "NO",
    //         "PA",
    //         "PY",
    //         "PE",
    //         "PH",
    //         "PL",
    //         "PT",
    //         "SG",
    //         "SK",
    //         "ES",
    //         "SE",
    //         "CH",
    //         "TW",
    //         "TR",
    //         "UY",
    //         "US",
    //         "GB",
    //         "AD",
    //         "LI",
    //         "MC",
    //         "ID",
    //         "JP",
    //         "TH",
    //         "VN",
    //         "RO",
    //         "IL",
    //         "ZA",
    //         "SA",
    //         "AE",
    //         "BH",
    //         "QA",
    //         "OM",
    //         "KW",
    //         "EG",
    //         "MA",
    //         "DZ",
    //         "TN",
    //         "LB",
    //         "JO",
    //         "PS",
    //         "IN",
    //         "BY",
    //         "KZ",
    //         "MD",
    //         "UA",
    //         "AL",
    //         "BA",
    //         "HR",
    //         "ME",
    //         "MK",
    //         "RS",
    //         "SI",
    //         "KR",
    //         "BD",
    //         "PK",
    //         "LK",
    //         "GH",
    //         "KE",
    //         "NG",
    //         "TZ",
    //         "UG",
    //         "AG",
    //         "AM",
    //         "BS",
    //         "BB",
    //         "BZ",
    //         "BT",
    //         "BW",
    //         "CV",
    //         "CW",
    //         "DM",
    //         "FJ",
    //         "GM",
    //         "GE",
    //         "GD",
    //         "GW",
    //         "GY",
    //         "HT",
    //         "JM",
    //         "KI",
    //         "LS",
    //         "LR",
    //         "MW",
    //         "MV",
    //         "ML",
    //         "MH",
    //         "FM",
    //         "NA",
    //         "NR",
    //         "NE",
    //         "PW",
    //         "PG",
    //         "WS",
    //         "SM",
    //         "ST",
    //         "SN",
    //         "SC",
    //         "SL",
    //         "SB",
    //         "KN",
    //         "LC",
    //         "VC",
    //         "SR",
    //         "TL",
    //         "TO",
    //         "TT",
    //         "TV",
    //         "VU",
    //         "AZ",
    //         "BI",
    //         "KH",
    //         "CM",
    //         "TD",
    //         "KM",
    //         "GQ",
    //         "SZ",
    //         "GA",
    //         "GN",
    //         "KG",
    //         "LA",
    //         "MO",
    //         "MR",
    //         "MN",
    //         "NP",
    //         "RW",
    //         "TG",
    //         "UZ",
    //         "ZW",
    //         "BJ",
    //         "MG",
    //         "MU",
    //         "MZ",
    //         "AO",
    //         "CI",
    //         "DJ",
    //         "ZM",
    //         "CD",
    //         "CG",
    //         "IQ",
    //         "LY",
    //         "TJ",
    //         "VE",
    //         "ET",
    //         "XK",
    //       ],
    //       disc_number: 1,
    //       duration_ms: 183703,
    //       explicit: true,
    //       external_ids: {
    //         isrc: "USUG11800947",
    //       },
    //       external_urls: {
    //         spotify: "https://open.spotify.com/track/1wa6QQsdSE3X2GbRljGpFk",
    //       },
    //       href: "https://api.spotify.com/v1/tracks/1wa6QQsdSE3X2GbRljGpFk",
    //       id: "1wa6QQsdSE3X2GbRljGpFk",
    //       is_local: false,
    //       name: "Candles",
    //       popularity: 68,
    //       preview_url: null,
    //       track_number: 10,
    //       type: "track",
    //       uri: "spotify:track:1wa6QQsdSE3X2GbRljGpFk",
    //     },
    //     currently_playing_type: "track",
    //     actions: {
    //       disallows: {
    //         resuming: true,
    //       },
    //     },
    //     is_playing: true,
    //   },
    // });

    const tk = await getToken({ req });
    if (tk) {
      const token = JSON.parse(JSON.stringify(tk, null, 2));

      spotifyApi.setAccessToken(token.access_token);

      const { body } = await spotifyApi.getMyCurrentPlaybackState();

      return res.status(200).json({ data: body });
    } else res.status(401).json({ error: "Unauthorized" });
  } catch (err: any) {
    return res.status(500).json(err.body.error);
  }
}
